spring:



  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  # The SQL dialect makes Hibernate generate better SQL for the chosen database




management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
      base-path: "/management-dashboard"
  endpoint:
    health:
      show-details: always


